// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define("app", function(require) {
  var $, App, Backbone, app;
  $ = require("jquery");
  Backbone = require("backbone");
  Backbone.Paginator = require("backbone.paginator");
  require("bootstrap");
  App = (function(_super) {

    __extends(App, _super);

    function App() {
      this.$win = window;
      this.$doc = this.$win.document;
      this.$body = this.$doc.body;
      this.el = $("#app");
    }

    return App;

  })(Backbone.View);
  app = new App();
  Backbone.Paginator.clientPager.prototype.whereExpanded = function(attrs) {
    return _.filter(this.origModels, function(model) {
      var key;
      for (key in attrs) {
        if (attrs[key] !== model.get(key)) {
          return false;
        }
      }
      return true;
    });
  };
  Backbone.emulateJSON = true;
  console.log("test");
  exports.app = app;
});
