// Generated by CoffeeScript 1.3.3

Inject.reset();

Inject.setModuleRoot("/javascripts/");

Inject.addRule(/^jquery$/, {
  path: "libs/jquery",
  pointcuts: {
    after: function() {
      module.setExports(jQuery.noConflict());
    }
  }
});

Inject.addRule(/^bootstrap$/, {
  path: "libs/bootstrap"
});

Inject.addRule(/^underscore$/, {
  path: "libs/underscore"
});

Inject.addRule(/^backbone$/, {
  path: "libs/backbone"
});
