// Generated by CoffeeScript 1.3.3

Inject.reset();

Inject.setModuleRoot("/javascripts/");

Inject.addRule(/^jquery$/, {
  path: "libs/jquery",
  pointcuts: {
    after: function() {
      module.setExports(jQuery.noConflict());
    }
  }
});

Inject.addRule(/^bootstrap$/, {
  path: "libs/bootstrap",
  pointcuts: {
    before: function() {
      var $;
      return $ = require("jquery");
    }
  }
});

Inject.addRule(/^underscore$/, {
  path: "libs/underscore"
});

Inject.addRule(/^backbone$/, {
  path: "libs/backbone"
});

Inject.addRule(/backbone\./, {
  path: function(module) {
    return "libs/backbone/" + module;
  },
  pointcuts: {
    before: function() {
      var Backbone;
      return Backbone = require("backbone");
    }
  }
});
